DROP TRIGGER IF EXISTS last_but_not_least ON DATABASE
GO

CREATE TRIGGER last_but_not_least
ON DATABASE
FOR ALTER_TABLE
AS

 DECLARE @IDTEACHER VARCHAR(50)
 DECLARE @ACTION1 VARCHAR(500)
 DECLARE @ACTION2 VARCHAR(500)
 DECLARE @ACTION3 VARCHAR(100)
 SELECT @IDTEACHER=EVENTDATA().value('(/EVENT_INSTANCE/AlterTableActionList/*/Columns/Name)[1]', 'nVARCHAR(100)') 
 
 IF @IDTEACHER='Id_Profesor'
 BEGIN
     SELECT @ACTION1 = EVENTDATA().value('(/EVENT_INSTANCE/TSQLCommand/CommandText)[1]','nVARCHAR(max)') 
     SELECT @ACTION3 = EVENTDATA().value('(/EVENT_INSTANCE/ObjectName)[1]','nVARCHAR(max)') 
     SELECT @ACTION2 = REPLACE(@ACTION1, @ACTION3, 'profesori');
   	EXECUTE (@ACTION2) 
     SELECT @ACTION2 = REPLACE(@ACTION1, @ACTION3, 'orarul');
   	 EXECUTE (@ACTION2) 
     SELECT @ACTION2 = REPLACE(@ACTION1, @ACTION3, 'studenti_reusita');
   	EXECUTE (@ACTION2)   
     PRINT 'DATA WAS MOTIFIED'   
 END;