DECLARE @N1 INT, @N2 INT, @N3 INT;
DECLARE @MAX INT;
SET @N1 = 60 * RAND();
SET @N2 = 60 * RAND();
SET @N3 = 60 * RAND();

SET @MAX = 
CASE 
	WHEN (@N1 > @N2 AND @N1 > @N2) THEN @N1
	WHEN (@N2 > @N3) THEN @N2
	ELSE @N3
END

PRINT @N1;
PRINT @N2;
PRINT @N3;
PRINT 'Mai mare = ' + CAST(@MAX AS VARCHAR(2));